server:
  port: 9005
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    trace-id128: true
    sampler:
      probability: 10.0
    propagation:
      propagation-keys: user_name

backendBaseUrl: http://localhost:9005

logging:
  pattern:
    level: "[${spring.application.name}, %X{traceId}/%X{spanId} %X{X-Span-Export:-}] %-5p [%t] %C{2} - %m%n"
  level:
    root: INFO
    org.springframework.web.servlet: INFO
    org.springframework.web: DEBUG
    com.davidparry: INFO
